---
version: '3.3'

services:
  booksapi:
    image: books_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: books_api
    environment:
      MY_TELEGRAM_BOT_TOKEN: ${MY_TELEGRAM_BOT_TOKEN}
    expose:
      - 8000
    networks:
      - kursova-network

networks:
  kursova-network:
    external:
      name: kursova-network
